name: parking-rl
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - gymnasium==0.29.1
      - numpy==1.23.5
      - matplotlib==3.7.1
      - torch==2.2.2
      - PyQt5==5.15.11
