name: parking-rl
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - numpy=1.23.5
  - matplotlib=3.7.1
  - ipykernel
  - ipython
  - notebook
  - pyqt>=5.15
  - pip
  - pip:
    - torch==2.2.2
      - gymnasium==0.29.1
