#!/usr/bin/env bash
set -euo pipefail

# Clean common Python build artifacts and metadata generated by editable installs.
# Usage: bash scripts/clean.sh

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")"/.. && pwd)"
cd "$ROOT_DIR"

echo "Cleaning __pycache__ directories..."
find . -type d -name "__pycache__" -prune -exec rm -rf {} +

echo "Cleaning *.egg-info directories..."
find . -type d -name "*.egg-info" -prune -exec rm -rf {} +

echo "Cleaning build/dist caches..."
rm -rf build dist .pytest_cache .mypy_cache .ruff_cache

echo "Done."

